# Generated by Django 4.2.7 on 2023-11-10 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Light'), ('Middleweight', 'Middle'), ('Cruiserweight', 'Cruiser'), ('Heavyweight', 'Heavy')], default='Lightweight', max_length=20)),
                ('weight_limit', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('battery_capacity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DroneModel',
                'verbose_name_plural': 'DroneModels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('code', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='drone_api.dronemodel')),
            ],
            options={
                'verbose_name': 'MedicationModel',
                'verbose_name_plural': 'MedicationModels',
                'ordering': ['-created_at'],
            },
        ),
    ]
