# Generated by Django 4.2.7 on 2023-11-09 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MedicationModel',
                'verbose_name_plural': 'MedicationModels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Light'), ('Middleweight', 'Middle'), ('Cruiserweight', 'Cruiser'), ('Heavyweight', 'Heavy')], default='Lightweight', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('battery_capacity', models.IntegerField(null=True)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicatios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_api.medicationmodel')),
            ],
            options={
                'verbose_name': 'DroneModel',
                'verbose_name_plural': 'DroneModels',
                'ordering': ['-created_at'],
            },
        ),
    ]
