# Generated by Django 4.2.7 on 2023-11-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronemodel',
            name='medicatios',
        ),
        migrations.AddField(
            model_name='medicationmodel',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_api.dronemodel'),
        ),
    ]
