# Generated by Django 4.2.7 on 2023-11-09 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0002_remove_dronemodel_medicatios_medicationmodel_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronemodel',
            name='battery_capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dronemodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='code',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='name',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$')]),
        ),
        migrations.AlterField(
            model_name='medicationmodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
