# Generated by Django 4.2.7 on 2023-11-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0003_alter_dronemodel_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationmodel',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='drone_api.dronemodel'),
        ),
    ]
